商品購入機能
Ogata0919/furima-29589 pull request #8
Opened 2021-01-27 09:12 UTC by Ogata0919

# What
商品購入機能の実装

# Why
商品を購入できるようにするため

2021-01-27 09:17 UTC, aoitech commented
レビュー依頼ありがとうございます。
こちらのプルリクエストですが、実際の画面や機能ができているか確認させていただきたいので、以下のキャプチャ動画をご提出いただけますか？
```
・購入に成功する動画
・購入が完了したら、トップページまたは購入完了ページに遷移する動画
・購入に失敗してエラーが表示させる動画
・ログアウト状態のユーザーが商品購入ページに遷移しようとすると、ログインページに遷移する動画
・ログイン状態の出品者が、URLを直接入力して自身の出品した商品購入ページに遷移しようとすると、トップページに遷移する動画
・出品者・出品者以外にかかわらず、ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移する動画
・ログアウト状態のユーザーが、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、ログインページに遷移する動画
・テスト結果の画像

```
「Gyazo　GIF　使い方」とgoogleで検索し、ツールによって生成されたURLをこのPRに貼っていただければ幸いです。
その後、再度レビュー依頼フォームにてプルリクエストURLのご提出いただけますでしょうか。
お手数をおかけいたしますが、よろしくお願いいたします。

2021-01-29 05:26 UTC, Ogata0919 commented
・購入に成功し購入が完了したら、トップページまたは購入完了ページに遷移する動画
https://gyazo.com/d8959f53f0b9414a373fec7bf54914c8
・購入に失敗してエラーが表示させる動画
https://gyazo.com/c4e4f48f6cce6b77b8e8f48a105ffb32
・ログアウト状態のユーザーが商品購入ページに遷移しようとすると、ログインページに遷移する動画
https://gyazo.com/be7b77fc2edcf5026da95a9665877bd4
・ログイン状態の出品者が、URLを直接入力して自身の出品した商品購入ページに遷移しようとすると、トップページに遷移する動画
https://gyazo.com/1535aa5f954e4bcebb377bec545a19ff
・出品者・出品者以外にかかわらず、ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移する動画
https://gyazo.com/24e5b9b7b3e31a51f85f35f16644f9db
・ログアウト状態のユーザーが、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、ログインページに遷移する動画
https://gyazo.com/231140ca65bc6ef65aeb30e88896ba0a
・テスト結果の画像
https://gyazo.com/4ddd3d8ed1a54fdf2941e46a47eaec4c

2021-01-29 05:29 UTC, norito0627 reviewed
レビュー依頼ありがとうございます！
コメントしましたので、ご確認をお願いいたします！

2021-01-29 05:29 UTC, norito0627 commented on app/controllers/purchase_controller.rb
> +  def index
「 URLを直接入力して購入済み商品の購入ページへ遷移しようとすると、トップページに遷移すること」
を満たす条件分岐を実装しましょう！

2021-01-29 06:52 UTC, Ogata0919 commented on app/controllers/purchase_controller.rb
> +  def index
実装しました！

2021-01-29 06:53 UTC, Ogata0919 commented on app/controllers/purchase_controller.rb
> +  def index
動画
https://gyazo.com/47b7b59bda4d5cf72b0a8dfb84871ec7

2021-01-29 07:07 UTC, chisesakai requested changes
レビュー依頼ありがとうございます。
修正点・gyazoともに確認させていただきました。
#### 追加で7件コメントいたしましたので、ご確認お願いいたします。

2021-01-29 07:07 UTC, chisesakai commented on app/controllers/purchase_controller.rb
> +  end
```ruby
    redirect_to root_path if current_user == @product.user || @product.purchase
  end
```
こちらは`create`アクションにも反映させましょう！
private以下にメソッド化し、before_actionで呼び出すのが良いかと思います。

2021-01-29 07:07 UTC, chisesakai commented on app/controllers/purchase_controller.rb
> +    @product = Product.find(params[:product_id])
```ruby
    @product = Product.find(params[:product_id])
```
5行目と11行目で定義している`@product`の記述が重複しているようです。
こちらはprivate以下にメソッド化して、beforeアクションで呼び出す形に修正しておきましょう。
複数回使用する変数をメソッド化することで可読性が上がり、改修作業が発生した際も手を加えやすくなります。

2021-01-29 07:07 UTC, chisesakai commented on app/controllers/purchase_controller.rb
> +    Payjp.api_key = ENV['PAYJP_SECRET_KEY'] # 自身のPAY.JPテスト秘密鍵を記述しましょう
```ruby
    Payjp.api_key = ENV['PAYJP_SECRET_KEY'] # 自身のPAY.JPテスト秘密鍵を記述しましょう
```
`# 自身のPAY.JPテスト秘密鍵を記述しましょう`
実装が完了した部分に関してはコメントアウトは削除しましょう！
もしメモとして残したい場合はこのままでも問題ございません。

2021-01-29 07:07 UTC, chisesakai commented on app/models/address_purchase.rb
> +    validates :token
```ruby
    validates :phone_number, format: { with: /\A((0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1}|[5789]0[-(]?\d{4})[-)]?)|\d{1,4}-?)\d{4}\z/, message: '電話番号を入力してください。' }
```
- 電話番号にはハイフンは不要で、11桁以内であること
と要件にありますので、バリデーションを変更しましょう！

2021-01-29 07:07 UTC, chisesakai commented on spec/factories/purchases.rb
> +end
使用していないFactoryBotのファイルは、不要であれば削除しましょう。
他のFactoryBotやspecファイルも同様に、不要なものは削除しましょう。

2021-01-29 07:07 UTC, chisesakai commented on app/models/address_purchase.rb
> +    validates :token
user_idとitem_idにも必須であるバリデーション(presence: true)を記述しましょう。
今まではモデル間のアソシエーションを組むことで、自動的にpresence: trueが働いておりました。
 ただ、フォームオブジェクトでは直接アソシエーションを組んでいないためにバリデーションが必要となります。

2021-01-29 07:07 UTC, chisesakai commented on spec/models/address_spec.rb
> +
モデルにuser_idとitem_idのバリデーションを追加した後は、テストにも以下の項目を実装しましょう！
```
・user_idが空では購入できないこと
・item_idが空では購入できないこと
```

2021-01-29 07:26 UTC, Ogata0919 commented on app/models/address_purchase.rb
> +    validates :token
完了

2021-01-29 07:28 UTC, Ogata0919 commented on app/models/address_purchase.rb
> +    validates :token
完了

2021-01-29 07:31 UTC, Ogata0919 commented on spec/factories/purchases.rb
> +end
完了

2021-01-29 07:31 UTC, Ogata0919 commented on app/controllers/purchase_controller.rb
> +    Payjp.api_key = ENV['PAYJP_SECRET_KEY'] # 自身のPAY.JPテスト秘密鍵を記述しましょう
完了

2021-01-29 09:09 UTC, Ogata0919 commented on app/controllers/purchase_controller.rb
> +  end
完了

2021-01-29 09:09 UTC, Ogata0919 commented on app/controllers/purchase_controller.rb
> +    @product = Product.find(params[:product_id])
完了

2021-01-29 09:10 UTC, Ogata0919 commented on spec/models/address_spec.rb
> +
完了しました
テストコード結果
https://gyazo.com/d2c16ab435c4362fd06811c463181d7b

2021-01-29 09:13 UTC, norito0627 commented
レビュー依頼ありがとうございます！
LGTMとさせていただきます！実装お疲れ様でした！マージしてから、次の実装に進んでください！引き続き実装頑張っていきましょう！

2021-01-29 09:15 UTC, merged